# Generated by Django 4.1.7 on 2024-03-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_sharedfolder_sharedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedfolder",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="sharedfolder",
            name="shared_by",
        ),
        migrations.RemoveField(
            model_name="sharedfolder",
            name="user",
        ),
        migrations.DeleteModel(
            name="SharedFile",
        ),
        migrations.DeleteModel(
            name="SharedFolder",
        ),
    ]
